name: FX Expiry Bot

on:
  schedule:
    - cron: '0 5 * * *'  # 8AM EAT daily
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run the bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python fx_option_bot.py
